[package]
name = "compact-bar"
version = "0.1.0"
authors = ["Alexander Kenji Berthold <aks.kenji@protonmail.com>" ]
edition.workspace = true
license.workspace = true

[dependencies]
ansi_term = { workspace = true }
unicode-width = { workspace = true }
zellij-tile = { path = "../../zellij-tile" }
zellij-tile-utils = { path = "../../zellij-tile-utils" }
