pub const COL_121: [&str; 20] = [
    "line1-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line2-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line3-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line4-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line5-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line6-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line7-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line8-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line9-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line10-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line11-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line12-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line13-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line14-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line15-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line16-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line17-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line18-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "line19-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n",
    "prompt $ ",
];

pub const COL_19: [&str; 20] = [
    "line1-bbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbb\n",
    "prompt $ ",
];

pub const COL_29: [&str; 20] = [
    "line1-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbbbbbbbbbbbb\n",
    "prompt $ ",
];

pub const COL_30: [&str; 20] = [
    "line1-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbbbbbbbbbbbbb\n",
    "prompt $ ",
];

pub const COL_40: [&str; 20] = [
    "line1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "prompt $ ",
];

pub const COL_50: [&str; 20] = [
    "line1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "prompt $ ",
];

pub const COL_60: [&str; 20] = [
    "line1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "prompt $ ",
];

pub const COL_70: [&str; 20] = [
    "line1-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line2-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line3-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line4-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line5-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line6-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line7-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line8-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line9-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line10-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line11-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line12-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line13-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line14-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line15-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line16-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line17-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line18-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "line19-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb\n",
    "prompt $ ",
];
