version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/zellij-client/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/zellij-server/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/zellij-tile-utils/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/zellij-tile/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/zellij-utils/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/default-plugins/status-bar/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/default-plugins/strider/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/default-plugins/tab-bar/"
    schedule:
      interval: "weekly"
