---
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    plugin: tab-bar
    events:
      - Tab
  - direction: Vertical
    expansion_boundary: true
  - direction: Vertical
    split_size:
      Fixed: 2
    plugin: status-bar
