[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true


[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
prost-build = { version = "0.12.6", default-features = false }
sha2 = { workspace = true }
toml = { version = "1.1.2", default-features = false, features = ["parse", "serde", "std"] }
which = "8"
xflags = { version = "0.3.2", default-features = false }
# TODO(hartan): Update this once we get a new release. See:
#   <https://github.com/matklad/xshell/issues/63>
xshell = { version = "= 0.2.2", default-features = false }

[lints.rust]
# Only required because we need to fix `xshell` to `=0.2.2`
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(trick_rust_analyzer_into_highlighting_interpolated_bits)'] }
