name: "\U0001F41B Bug Report"
description: Report a bug or issue with Zellij
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Please note:** Comparisons of desired behavior to tmux are usually not relevant. tmux and Zellij are two extremely different programs that do things very differently. Zellij is not, nor does it try to be, a tmux clone. Please try to refrain from such comparisons.

        Please choose the relevant section below and provide the requested information.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What type of issue are you reporting?
      options:
        - Graphical issue inside a terminal pane
        - Zellij UI / behavior / crash issue
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Instructions Based on Issue Type

        ### For Type 1: Graphical Issues in Terminal Panes

        If you selected "Graphical issue inside a terminal pane", please follow these steps:

        1. Delete the contents of `/tmp/zellij-1000/zellij-log` with `cd /tmp/zellij-1000/` and `rm -fr zellij-log/` (use `$TMPDIR/` on macOS)
        2. Run `zellij --debug`
        3. Run `stty size`, copy the result and fill in the field below
        4. Recreate your issue
        5. Quit Zellij immediately with ctrl-q (your bug should ideally still be visible on screen)
        6. Attach the files created in `/tmp/zellij-1000/zellij-log/` in the "Other Relevant Information" section

        ### For Type 2: Zellij UI / Behavior / Crash Issues

        Please find a minimal reproduction. If you have a complex setup that causes an issue, try to troubleshoot and narrow the problem down to as minimal a reproduction as possible. Remove as many parts of the equation as you can.

        If you are unsure what to do, you are welcome to ask for help either in the issue itself or in one of our community chats (Discord / Matrix). We will be happy to try and assist or suggest directions, but please note that the responsibility to troubleshoot the issue and find the problem is ultimately on your shoulders. For the removal of doubt: a Zellij stack-trace is enough of a reproduction (although further details will always be appreciated).

        **Example of a good issue report:** "The `default_tab_template` layout node does not work when resurrecting sessions"

        **Example of an issue report that needs work:** "Zellij randomly crashes without an error when I use it with the attached script"

        ---

  - type: textarea
    id: basic_info_version
    attributes:
      label: Zellij Version
      description: Output of `zellij --version`
      placeholder: "zellij 0.40.1"
    validations:
      required: true

  - type: textarea
    id: basic_info_stty
    attributes:
      label: stty size (Required for Type 1 - Graphical issues only)
      description: Output of `stty size` command. Leave blank if reporting Type 2 issue.
      placeholder: "24 80"
    validations:
      required: false

  - type: textarea
    id: basic_info_system
    attributes:
      label: System Information
      description: Output of `uname -av` (Unix/Linux/macOS) or `ver` (Windows)
      placeholder: "Linux hostname 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Provide a clear and concise description of the issue
      placeholder: |
        For Type 1 (Graphical): Describe what doesn't look right in the terminal pane...
        For Type 2 (UI/Behavior/Crash): Describe what's happening...
    validations:
      required: true

  - type: textarea
    id: minimal_reproduction
    attributes:
      label: Reproduction Steps / Further Information
      description: |
        **For Type 1 (Graphical issues):** Describe the steps to reproduce, noticeable behavior, related issues, etc.
        **For Type 2 (UI/Behavior/Crash):** Provide minimal reproduction steps. Include configuration files, commands, or scripts if relevant.
      placeholder: |
        1. Start Zellij with...
        2. Run command...
        3. Observe behavior...
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Other Relevant Information
      description: |
        - **For Type 1:** Attach log files from `/tmp/zellij-1000/zellij-log/` here
        - **For Type 2:** Add any additional context, screenshots, logs, or stack traces

        You can attach files by dragging and dropping them here.
      placeholder: Attach logs, screenshots, or provide additional context...
    validations:
      required: false

