[package]
name = "plugin-manager"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition.workspace = true

[dependencies]
uuid = { version = "1.7.0", features = ["v4"] }
fuzzy-matcher = "0.3.7"
zellij-tile = { path = "../../zellij-tile" }
