[package]
name = "strider"
version = "0.2.0"
authors = ["Brooks J Rady <b.j.rady@gmail.com>"]
edition.workspace = true
description = "A simplified ranger clone written as a Zellij plugin"
license.workspace = true

[dependencies]
zellij-tile = { path = "../../zellij-tile" }
pretty-bytes = { workspace = true }
fuzzy-matcher = { workspace = true }
unicode-width = { workspace = true }
