#!/bin/bash

log_file="${1:-log.txt}"
log_file_path="/tmp/mosaic/mosaic-log/${log_file}"

[[ -f $log_file_path ]] && rm "${log_file_path}"
printf "\n%${COLUMNS}s" | tr " " "-"
tail -F "${log_file_path}"
