// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Slot {
    #[prost(uint32, tag="1")]
    pub id: u32,
    #[prost(enumeration="SlotKind", tag="2")]
    pub kind: i32,
    #[prost(message, optional, tag="3")]
    pub configuration: ::core::option::Option<super::action::PluginConfiguration>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventContext {
    #[prost(uint32, optional, tag="1")]
    pub slot_id: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag="2")]
    pub client_id: ::core::option::Option<u32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenderRequest {
    #[prost(enumeration="RenderKind", tag="1")]
    pub kind: i32,
    #[prost(uint32, optional, tag="2")]
    pub client_id: ::core::option::Option<u32>,
    #[prost(uint32, repeated, tag="3")]
    pub slot_ids: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SlotKind {
    Pane = 0,
    Background = 1,
}
impl SlotKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SlotKind::Pane => "Pane",
            SlotKind::Background => "Background",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Pane" => Some(Self::Pane),
            "Background" => Some(Self::Background),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RenderKind {
    Nothing = 0,
    All = 1,
    Client = 2,
    Slots = 3,
}
impl RenderKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RenderKind::Nothing => "Nothing",
            RenderKind::All => "All",
            RenderKind::Client => "Client",
            RenderKind::Slots => "Slots",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Nothing" => Some(Self::Nothing),
            "All" => Some(Self::All),
            "Client" => Some(Self::Client),
            "Slots" => Some(Self::Slots),
            _ => None,
        }
    }
}
