// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptRequest {
    #[prost(string, tag="1")]
    pub element: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint64, optional, tag="3")]
    pub timeout_ms: ::core::option::Option<u64>,
    #[prost(string, optional, tag="4")]
    pub default: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, optional, tag="5")]
    pub placement: ::core::option::Option<PromptPlacement>,
    #[prost(bool, tag="6")]
    pub focused: bool,
    #[prost(oneof="prompt_request::Spec", tags="7, 8, 9, 10, 11, 12, 13, 14, 15")]
    pub spec: ::core::option::Option<prompt_request::Spec>,
}
/// Nested message and enum types in `PromptRequest`.
pub mod prompt_request {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Spec {
        #[prost(message, tag="7")]
        Confirm(super::ConfirmSpec),
        #[prost(message, tag="8")]
        Choose(super::ChooseSpec),
        #[prost(message, tag="9")]
        Input(super::InputSpec),
        #[prost(message, tag="10")]
        Number(super::NumberSpec),
        #[prost(message, tag="11")]
        Toggle(super::ToggleSpec),
        #[prost(message, tag="12")]
        Select(super::SelectSpec),
        #[prost(message, tag="13")]
        Menu(super::MenuSpec),
        #[prost(message, tag="14")]
        Form(super::FormSpec),
        #[prost(message, tag="15")]
        Notify(super::NotifySpec),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptPlacement {
    #[prost(enumeration="PromptPlacementKind", tag="1")]
    pub kind: i32,
    #[prost(uint32, optional, tag="2")]
    pub pane_id: ::core::option::Option<u32>,
    #[prost(bool, tag="3")]
    pub pane_is_plugin: bool,
    #[prost(string, optional, tag="4")]
    pub corner: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChoiceItem {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
    #[prost(string, optional, tag="2")]
    pub label: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfirmSpec {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<super::style::StyledText>,
    #[prost(string, tag="2")]
    pub yes: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub no: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChooseSpec {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<ChoiceItem>,
    #[prost(bool, tag="2")]
    pub multi: bool,
    #[prost(string, repeated, tag="3")]
    pub selected: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InputSpec {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<super::style::StyledText>,
    #[prost(string, optional, tag="2")]
    pub placeholder: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="3")]
    pub validate: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, tag="4")]
    pub required: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NumberSpec {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<super::style::StyledText>,
    #[prost(int64, optional, tag="2")]
    pub min: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="3")]
    pub max: ::core::option::Option<i64>,
    #[prost(int64, tag="4")]
    pub step: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToggleSpec {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<super::style::StyledText>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectSpec {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<super::style::StyledText>,
    #[prost(string, repeated, tag="2")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MenuSpec {
    #[prost(message, repeated, tag="1")]
    pub items: ::prost::alloc::vec::Vec<ChoiceItem>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FormField {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration="FormFieldKind", tag="2")]
    pub kind: i32,
    #[prost(string, tag="3")]
    pub label: ::prost::alloc::string::String,
    #[prost(bool, tag="4")]
    pub required: bool,
    #[prost(string, optional, tag="5")]
    pub validate: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="6")]
    pub placeholder: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, repeated, tag="7")]
    pub options: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag="8")]
    pub multi: bool,
    #[prost(int64, optional, tag="9")]
    pub min: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="10")]
    pub max: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="11")]
    pub step: ::core::option::Option<i64>,
    #[prost(string, optional, tag="12")]
    pub default_json: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FormSpec {
    #[prost(string, optional, tag="1")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag="2")]
    pub fields: ::prost::alloc::vec::Vec<FormField>,
    #[prost(string, tag="3")]
    pub submit_label: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub cancel_label: ::prost::alloc::string::String,
    #[prost(message, optional, tag="5")]
    pub message: ::core::option::Option<super::style::StyledText>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NotifySpec {
    #[prost(message, optional, tag="1")]
    pub message: ::core::option::Option<super::style::StyledText>,
    #[prost(bool, tag="2")]
    pub show_pane_name: bool,
    #[prost(bool, tag="3")]
    pub show_tab_name: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptValueList {
    #[prost(string, repeated, tag="1")]
    pub values: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptFormEntry {
    #[prost(string, tag="1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub value: ::core::option::Option<PromptValue>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptFormValue {
    #[prost(message, repeated, tag="1")]
    pub entries: ::prost::alloc::vec::Vec<PromptFormEntry>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptValue {
    #[prost(oneof="prompt_value::Value", tags="1, 2, 3, 4, 5, 6")]
    pub value: ::core::option::Option<prompt_value::Value>,
}
/// Nested message and enum types in `PromptValue`.
pub mod prompt_value {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag="1")]
        Text(::prost::alloc::string::String),
        #[prost(int64, tag="2")]
        Number(i64),
        #[prost(bool, tag="3")]
        BoolValue(bool),
        #[prost(string, tag="4")]
        Choice(::prost::alloc::string::String),
        #[prost(message, tag="5")]
        Choices(super::PromptValueList),
        #[prost(message, tag="6")]
        Form(super::PromptFormValue),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptTimedOut {
    #[prost(message, optional, tag="1")]
    pub value: ::core::option::Option<PromptValue>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptCancelled {
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PromptResult {
    #[prost(oneof="prompt_result::Result", tags="1, 2, 3, 4, 5")]
    pub result: ::core::option::Option<prompt_result::Result>,
}
/// Nested message and enum types in `PromptResult`.
pub mod prompt_result {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag="1")]
        Answered(super::PromptValue),
        #[prost(bool, tag="2")]
        Confirmed(bool),
        #[prost(message, tag="3")]
        Cancelled(super::PromptCancelled),
        #[prost(message, tag="4")]
        TimedOut(super::PromptTimedOut),
        #[prost(string, tag="5")]
        Error(::prost::alloc::string::String),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PromptPlacementKind {
    Pane = 0,
    Center = 1,
    Mouse = 2,
    Cursor = 3,
    Corner = 4,
}
impl PromptPlacementKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            PromptPlacementKind::Pane => "Pane",
            PromptPlacementKind::Center => "Center",
            PromptPlacementKind::Mouse => "Mouse",
            PromptPlacementKind::Cursor => "Cursor",
            PromptPlacementKind::Corner => "Corner",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Pane" => Some(Self::Pane),
            "Center" => Some(Self::Center),
            "Mouse" => Some(Self::Mouse),
            "Cursor" => Some(Self::Cursor),
            "Corner" => Some(Self::Corner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FormFieldKind {
    Input = 0,
    Select = 1,
    Toggle = 2,
    Number = 3,
    Choose = 4,
}
impl FormFieldKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FormFieldKind::Input => "Input",
            FormFieldKind::Select => "Select",
            FormFieldKind::Toggle => "Toggle",
            FormFieldKind::Number => "Number",
            FormFieldKind::Choose => "Choose",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Input" => Some(Self::Input),
            "Select" => Some(Self::Select),
            "Toggle" => Some(Self::Toggle),
            "Number" => Some(Self::Number),
            "Choose" => Some(Self::Choose),
            _ => None,
        }
    }
}
