// This file contains conversion code between `CommandToRun` and `ProtobufCommand`
// `CommandToRun` - this is the struct used by both Zellij and Rust plugins
// `ProtobufCommand` - this is the struct generated by the `.proto` file and used for serialization
// across the wasm boundary
//
// SDK authors in other languages should generate their own equivalent structures based on the
// `.proto` specification, and then decode the protobuf over the wire into them

pub mod api {
    // this is a compile time asset generated from the `.proto` specification file by Prost to give
    // us the ProtobufCommand structure we are gathered here to avoid
    include!(concat!(env!("OUT_DIR"), "/api.resize.rs"));
}

pub use api::{Resize as ProtobufResize, ResizeAction, resize::OptionalDirection};
use crate::data::{Resize, Direction};

use std::convert::TryFrom;
use std::path::PathBuf;

impl TryFrom<ProtobufResize> for Resize {
   type Error = &'static str;
   fn try_from(protobuf_resize: ProtobufResize) -> Result<Self, &'static str> {
       // TODO: CONTINUE HERE - implement this, then continue in zellij_exports.rs
       if protobuf_resize.optional_direction.is_some() {
           return Err("Resize cannot have a direction");
       }
       let name = protobuf_message.name;
       let payload = protobuf_message.payload;
       let worker_name = protobuf_message.optional_worker_name.map(|n| {
           match n {
               OptionalWorkerName::WorkerName(n) => n
           }
       });
       Ok(PluginMessage {
           name,
           payload,
           worker_name
       })
   }
}

impl TryFrom<PluginMessage> for ProtobufMessage {
   type Error = &'static str;
   fn try_from(plugin_message: PluginMessage) -> Result<Self, &'static str> {
       Ok(ProtobufMessage {
           name: plugin_message.name,
           payload: plugin_message.payload,
           optional_worker_name: plugin_message.worker_name.map(|n| OptionalWorkerName::WorkerName(n))
       })
   }
}
