[package]
name = "layout-manager"
version = "0.1.0"
authors = ["Aram Drevekenin <aram@poor.dev>"]
edition.workspace = true
license.workspace = true

[dependencies]
zellij-tile = { path = "../../zellij-tile" }
miette = { workspace = true }
strip-ansi-escapes = { workspace = true }
unicode-width = { workspace = true }
fuzzy-matcher = { workspace = true }
